version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_system
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
     - "3307:3206"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
     - ".:/chat_system"
    ports:
     - "3001:3000"
    depends_on:
     - db
    links:
     - db
    environment:
      DB_USER: root
      DB_NAME: chat_system
      DB_PASSWORD: password
      DB_HOST: db